export const API_URL = 'https://dmeserver.herokuapp.com/api';
// export const API_URL = 'http://localhost:8080/api';

export const METHOD_GET = 'METHOD_GET';
export const METHOD_POST = 'METHOD_POST';
export const METHOD_PUT = 'METHOD_PUT';
export const METHOD_DELETE = 'METHOD_DELETE';

export const ON_LOAD = 'ON_LOAD';
export const OFF_LOAD = 'OFF_LOAD';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const NOTIFICATION_INFO = 'NOTIFICATION_INFO';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';


export const LOAD_RESTAURANT = 'LOAD_RESTAURANT';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_MENUS = 'FETCH_MENUS';

export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';

export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const EDIT_USER = 'EDIT_USER';
export const SET_IMAGE_USER = 'SET_IMAGE_USER';
export const DELETE_IMAGE_USER = 'DELETE_IMAGE_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const LOAD_RESTAURANTS_FROM_USER = 'LOAD_RESTAURANTS_FROM_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const ASOCIATE_RESTAURANT = 'ASOCIATE_RESTAURANT';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const LOAD_ORDER = 'LOAD_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';